config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'my_music_playlist#index', as: 'my_music_playlist'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :playlists do
    resources :songs
  end

  resources :songs


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :playlist
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end      
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || my_music_playlist_path
  end
end

app/controllers/my_music_playlist_controller.rb
class MyMusicPlaylistController < ApplicationController

  def index
    @playlists = Playlist.all
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :index]

  def new
    @playlist = Playlist.new
  end

  def show
    @playlist = Playlist.find(params[:id])
    @songs = Song.where(:playlist_id => params[:id])
  end

  def index
    @playlists = Playlist.all
  end

  def create
    @playlist = Playlist.new(playlist_params)
    if @playlist.save
      flash[:notice] = 'Playlist successfully saved'
      redirect_to playlists_path
    else
      flash[:alert] = 'Playlist could not be created'
      render 'new'
    end
  end

  private

  def playlist_params
    params.require(:playlist).permit(:title)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def new
    @song = Song.new
  end

  def create
    @song = Song.new
    @song.uri = params[:uri]
    @song.playlist_id = params[:playlist_id]
    @song.save
    

  end

  private

  def comment_params
    params.require(:song).permit(:playlist_id, :uri)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
     @user = User.from_omniauth(request.env["omniauth.auth"])
     sign_in_and_redirect @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_music_playlist_helper.rb
module MyMusicPlaylistHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
    <ul class="nav navbar-nav">
        <li> <%= link_to "Playlist Home", my_music_playlist_path %> </li>
        <% if !user_signed_in? %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Playlist", playlists_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
        <% end %>
    </ul>

    <% if user_signed_in? %>
     <p class="navbar-text navbar-right" style ="margin-right: 15px;">Signed in as <%= link_to current_user.email, edit_user_registration_path %> </b></p>
     <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Music Playlist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
  <%= render 'layouts/header' %>
 <div class="container">
   <div class="row">
     <%= content_tag(:div, flash[:error], :class => "alert alert-warning") if flash[:error] %>
     <%= content_tag(:div, flash[:notice], :class => "alert alert-success") if flash[:notice] %>
     <%= content_tag(:div, flash[:alert], :class => "alert alert-danger") if flash[:alert] %>
     <div id="printAlert"></div>
     <div class="col-md-1"></div>
     <div class="col-md-10">
       <div class="jumbotron"><%= yield %>
       </div>
     </div>
     <div class="col-md-1"></div>
   </div>
 </div>
  </body>
</html>

app/views/my_music_playlist/index.html.erb
<h2>  </h2>
<ul>
  <% @playlists.each do |p| %>
    <li><%= link_to p.title, playlist_path(p.id)  %></li>
  <% end %>
</ul>

app/views/playlists/_form.html.erb
<%= form_for @playlist do |f| %>
<% if @playlist.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this category from being saved:</h2>

    <ul>
    <% @playlist.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="field">
  <%= f.text_field :title %>
</div>
<div class="actions">
  <%= f.submit %>
</div>

<% end %>

app/views/playlists/index.html.erb
<h3><%= link_to "Create New Playlist", new_playlist_path %></h3>

<h2> Playlists </h2>
<ul>
  <% @playlists.each do |p| %>
    <li><%= link_to p.title, playlist_path(p.id)  %></li>
  <% end %>
</ul>

app/views/playlists/new.html.erb
<h2> Create New Playlist </h2>

<%= render partial: 'form', locals: {playlist: @playlist} %>

app/views/playlists/show.html.erb
<h2> <%= @playlist.title %></h2>

<ul>
  <% @songs.each do |s| %>
    <li><iframe src="https://embed.spotify.com/?uri=spotify:track:<%= s.uri  %>" width="250" height="300" frameborder="0" allowtransparency="true"></iframe></li>
  <% end %>
</ul>


<h3> Search a Song </h3>

<input type="text" id="searchSong" name="searchSong">
<br><br>
<div id="showSongs"></div>

app/views/songs/new.html.erb
<%= render partial: 'projects/form', locals: { song: @song } %>